---
- name: Configure media as NFS mount
  hosts: media-server
  tasks:
    - name: Override default var-mnt-media.mount
      ansible.builtin.template:
        src: nfs_var-mnt-media.mount.j2
        dest: /etc/systemd/system/var-mnt-media.mount
        owner: root
        group: root
        mode: u=rw,go=r
