# original source: https://github.com/gbraad-dotfiles/upstream/blob/refs/heads/main/.github/workflows/build-diskimage-almalinux-upload.yml
name: build disk qcow

on:
  workflow_dispatch:

jobs:
  build:
    name: Build disk qcow
    runs-on: ubuntu-24.04

    steps:
    - name: Free up disk space
      uses: gbraad-actions/remove-unwanted@v1

    - uses: actions/checkout@v4

    - name: Workaround podman issues in GH actions
      run: |
        # see https://github.com/osbuild/bootc-image-builder/issues/446
        sudo rm -rf /var/lib/containers/storage
        sudo mkdir -p /etc/containers
        echo -e "[storage]\ndriver = \"overlay\"\nrunroot = \"/run/containers/storage\"\ngraphroot = \"/var/lib/containers/storage\"" | sudo tee /etc/containers/storage.conf

    - name: Workarounds for GH runner diskspace
      run: |
        sudo mkdir -p /mnt/var/lib/containers
        sudo mount -o bind /mnt/var/lib/containers /var/lib/containers
        sudo mkdir /var/lib/containers/storage

    - name: Build disk image
      id: build-image-dotfiles
      run: |
        mkdir -p ./output
        sudo podman pull ghcr.io/${{ github.repository }}:latest
        sudo podman run \
          --rm \
          --privileged \
          --pull=newer \
          --security-opt label=type:unconfined_t \
          -v ./config.toml:/config.toml:ro \
          -v ./output:/output \
          -v /var/lib/containers/storage:/var/lib/containers/storage \
          quay.io/centos-bootc/bootc-image-builder:latest \
          --progress verbose \
          --target-arch amd64 \
          --type qcow2 \
          --rootfs xfs \
          ghcr.io/${{ github.repository }}:latest

    - name: Rename output file
      run: sudo mv ./output/qcow2/disk.qcow2 ./output/qcow2/${{ github.event.repository.name }}-disk.qcow2

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-disk
        path: |
          ./output/qcow2/${{ github.event.repository.name }}-disk.qcow2
        retention-days: 5
